display_name: Lemonade Controller

icon: linux/assets/app_icon.png
summary: Desktop app for managing AI models on a Lemonade Server
group: Applications/Development
vendor: Samuel Tee
packager: Samuel Tee
packagerEmail: samuel_tee_gy@hotmail.com
url: https://github.com/Kidsnd274/lemonade_controller

keywords:
  - Lemonade Controller

generic_name: API Client

categories:
  - Development
  - Utility

startup_notify: true
