display_name: Lemonade Controller
package_name: lemonade-controller

maintainer:
  name: Samuel Tee
  email: samuel_tee_gy@hotmail.com

priority: optional

section: x11

installed_size: 52236

essential: false

icon: linux/assets/app_icon.png
startup_wm_class: com.kidsnd274.LemonadeController

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - Lemonade Controller

generic_name: API Client

categories:
  - Development
  - Utility

startup_notify: true